defaults:
  - _self_
  - detr
  - yolos

hydra:
  run:
    dir: C:\Users\pietr\PycharmProjects\idus\outputs

model: null
seed: 42
numGroups: 8
numClass: 8
growthRate: 32
currentDir: ${hydra:runtime.cwd}
inChans: 3

# MARK: - yolo dataset
targetHeight: 608
targetWidth: 608

# MARK: - miscellaneous
device: cuda
weight: ""


# MARK: - training config
lr: 1e-4
lrBackbone: 1e-5
batchSize: 32
weightDecay: 1e-5
epochs: 100
lrDrop: 50
clipMaxNorm: .1
patience: 15

# MARK: - loss
classCost: 1
bboxCost: 5
giouCost: 2
eosCost: 0

# MARK: - dataset
dataset: "kitti"
dataDir: ${hydra:runtime.cwd}\data\
trainAnnFile: ${hydra:runtime.cwd}/data/new/Train.json
valAnnFile: ${hydra:runtime.cwd}/data/new/Valid.json
testAnnFile: ${hydra:runtime.cwd}/data/new/Test.json

#MARK: - unlearning
excludeClasses: []
unlearningType: "CR"
unlearningMethod: ""
multiplier: 1

# MARK: - miscellaneous
outputDir: ${hydra:runtime.cwd}\checkpoint
numWorkers: 7
multi: False
amp: False

# MARK: - wandb
wandbEntity: p-manco-universit-di-pisa
wandbProject: idus
