defaults:
  - _self_
  - detr
  - yolos

hydra:
  run:
    dir: C:\Users\pietr\PycharmProjects\idus\outputs

model: null
seed: 42
numGroups: 8
excludeClasses: []
numClass: 37
growthRate: 32
currentDir: ${hydra:runtime.cwd}
inChans: 3

# MARK: - yolo dataset
targetHeight: 608
targetWidth: 608

# MARK: - miscellaneous
device: cuda
weight: ""


# MARK: - training config
lr: 1e-4
lrBackbone: 1e-5
batchSize: 32
weightDecay: 1e-4
epochs: 100
lrDrop: 50
clipMaxNorm: .1
patience: 15

# MARK: - loss
classCost: 5
bboxCost: 0.5
giouCost: 0.5
eosCost: 0

# MARK: - dataset
dataset: "oxford-pet"
dataDir: ${hydra:runtime.cwd}/data/
trainAnnFile: ${hydra:runtime.cwd}/data/new/Train.json
valAnnFile: ${hydra:runtime.cwd}/data/new/Valid.json
testAnnFile: ${hydra:runtime.cwd}/data/new/Test.json

# MARK: - miscellaneous
outputDir: ${hydra:runtime.cwd}/checkpoint
numWorkers: 7
multi: False
amp: False

# MARK: - wandb
wandbEntity: p-manco-universit-di-pisa
wandbProject: idus
